CREATE TABLE "User" (
  "id" TEXT PRIMARY KEY,
  "email" TEXT UNIQUE NOT NULL,
  "fullName" TEXT,
  "phone" TEXT,
  "avatar" TEXT,
  "subscriptionTier" TEXT DEFAULT 'free',
  "subscriptionStatus" TEXT DEFAULT 'active',
  "subscriptionId" TEXT,
  "planId" TEXT,
  "monthlyCredits" INTEGER DEFAULT 10,
  "practiceCredits" INTEGER DEFAULT 0,
  "creditsUsed" INTEGER DEFAULT 0,
  "creditsReset" TIMESTAMPTZ,
  "industry" TEXT,
  "businessType" TEXT,
  "brandName" TEXT,
  "brandIndustry" TEXT,
  "brandAesthetic" TEXT,
  "brandColors" TEXT[],
  "brandRequirements" TEXT,
  "emailNotifications" BOOLEAN DEFAULT true,
  "whatsappNotifications" BOOLEAN DEFAULT false,
  "whatsappNumber" TEXT,
  "language" TEXT DEFAULT 'en',
  "timezone" TEXT DEFAULT 'UTC',
  "hasCompletedOnboarding" BOOLEAN DEFAULT false,
  "setupFeesPaid" BOOLEAN DEFAULT false,
  "onboardingStep" INTEGER DEFAULT 0,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW(),
  "lastLoginAt" TIMESTAMPTZ,
  "lastActiveAt" TIMESTAMPTZ
);